### PR TITLE
Add FASTTLD_NO_AUTO_UPDATE option

### PR DESCRIPTION
**Pull request by earada**
In some network restricted environments it will be great to have a way to disable the autoupdate.

This small fix adds a check. If there is an environment variable `FASTTLD_NO_AUTO_UPDATE=1`  then it skips the update.

### CODE REVIEW

**Comment by jophy** [comment]
I will improve it.

**Comment by earada** [comment]
Thanks a lot @jophy !!
The ticket got closed when I clone the elliotwutingfeng fork. But it would be a great option to have.

**Comment by elliotwutingfeng** [comment]
@earada My pull request has been accepted and merged. Feel free to make your pull request directly to @jophy's repo. Would recommend adding a statement about `FASTTLD_NO_AUTO_UPDATE` to the readme as well.

**Comment by earada** [comment]
Great! I'll switch the repo back again and then create a PR with some changes!

**Pull request closed without merging**
